### ISSUE TITLE
`@compat` for `[]`?

### ISSUE THREAD

**Issue by garrison** [JuliaLang/Compat.jl#102]
In julia `0.4`, the `{}` syntax is deprecated:

```
julia> {}

WARNING: deprecated syntax "{}".
Use "[]" instead.
0-element Array{Any,1}
```

Changing `{}` to `[]` leads to the correct behavior on julia `0.4`.  However, on julia `0.3` it results in a different type, `Array{None,1}`:

```
julia> []
0-element Array{None,1}
```

I think one of two things should be done:

1. Make `@compat []` transform to `Any[]` on julia `0.3`; or,
2. Make the deprecation notice suggest using `Any[]` instead of `[]` in place of `{}`.

(If the second option makes more sense, this bug should really be filed against julia instead.)

Also, apologies if this has been discussed elsewhere; it's a fairly difficult issue to search for.

**Comment by sbromberger** [comment]
Does this work for the array rewrite? (This is my first attempt at metaprogramming; my tests seem to work but there may be edge cases).

I don't know where to put this, in any case.

`Vector` appears to be a `:ref` instead of a `:call` so there will likely need to be another function.

```
function rewrite_arr(ex)
    f = ex.args[1]
    if isexpr(f, :curly)
        head = ex.head
        args = [f.args[1:2], ex.args[2:end]]
        return Expr(head, args...)
    else
        return ex
    end
end
```

**Comment by stevengj** [comment]
The second option makes more sense to me.  Compat is only needed if there is no syntax already that works with both versions.

**Comment by sbromberger** [comment]
Given @StefanKarpinski's comments in https://github.com/JuliaLang/Compat.jl/issues/105#issuecomment-114126840, does it make more sense to suggest using `Array{Any}(0)` once #105 gets finished?

**Comment by stevengj** [comment]
No, I don't think we should speculate about future syntax changes.  The deprecation warning seems like a bug in Julia that should be fixed.

**Comment by IainNZ** [comment]
The deprecation warning is correct: on 0.4 you should use `[]`. The `Any[]` advice is only useful for 0.3 code, which 0.4 isn't concerned with. Or am I thinking about this the wrong way round?

**Comment by mbauman** [comment]
This does seem like a place where `@compat` could be useful, regardless of what the deprecation warning says.

A supported way to get an `Any` array in 0.4 is `[]`.  This isn't what happens in 0.3.  So let's allow 0.3 and 0.4 to work the same way with `@compat`.

**Comment by kmsquire** [comment]
Can someone point to the commit where `[]` was changed from `None[]` to `Any[]`?

**Comment by stevengj** [comment]
I think it was JuliaLang/julia#8493
