### ISSUE TITLE
@compat(BLAS.BlasInt(5))

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/Compat.jl#104]
This should be BLAS.blas_int(5) in 0.3.

**Comment by stevengj** [comment]
Since this isn't even documented in Julia, I'm not sure it really belongs in Compat; you could always put the requisite `BlasInt` function in a module where you need this compatibility.

**Comment by dlfivefifty** [comment]
I ended up removing the BlasInt conversion call: regular ints seem to work.  

The usage was a wrapper for the LAPack routine zhseqr_, which mimiced the Base/LinAlg/LAPack.jl implementations



Cheers,
Sheehan

**Comment by stevengj** [comment]
`ccall` will do the conversions for you, but you need to declare the correct type (`BlasInt`) in the argument list.   (`Int` may or may not work depending on what BLAS implementation you link.)

**Comment by dlfivefifty** [comment]
Yes I left the declaration as BlasInt, which works in both 0.4 and 0.3
