### ISSUE TITLE
#110 doesn't rewrite properly

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/Compat.jl#111]
Consider:

```
julia> macroexpand(:(TarjanVisitor(n::Int) = TarjanVisitor(
                         @compat Vector{Int}(),
                         @compat Vector{Int}(),
                         zeros(Int, n),
                         @compat Vector{Vector{Int}}()
              )))
:(TarjanVisitor(n::Int) = begin  # none, line 1:
            TarjanVisitor((Vector{Int}(),(Vector{Int}(),zeros(Int,n),Vector{Vector{Int}}())))
        end)

julia> macroexpand(:(@compat TarjanVisitor(n::Int) = TarjanVisitor(
                         Vector{Int}(),
                         Vector{Int}(),
                         zeros(Int, n),
                         Vector{Vector{Int}}()
                     )))
:(TarjanVisitor(n::Int) = begin  # none, line 1:
            TarjanVisitor(Vector{Int}(),Vector{Int}(),zeros(Int,n),Vector{Vector{Int}}())
        end)
```

When `@compat` is placed BEFORE the beginning of the constructor, things are fine. When `@compat` is used WITHIN the constructor, things fail (see  https://travis-ci.org/JuliaGraphs/LightGraphs.jl/builds/69349027 for an example).

**Comment by sbromberger** [comment]
A simpler case that shows what appears to be incorrect nesting of parens (second example):

```
julia> macroexpand(:(@compat Foo(n::Int) = Vector{Int}(), Vector{Int}(), Int))
:(Foo(n::Int) = begin  # none, line 1:
            (Vector{Int}(),Vector{Int}(),Int)
        end)

julia> macroexpand(:(Foo(n::Int) = @compat Vector{Int}(), @compat Vector{Int}(), Int))
:(Foo(n::Int) = begin  # none, line 1:
            (Vector{Int}(),(Vector{Int}(),Int))
        end)
```

**Comment by simonster** [comment]
This is just the way macros are. `@macro x, y` parses as `@macro((x, y))` and not `@macro(x),y`. This has tripped people up before (e.g. #71), but there's nothing we can do about it in Compat, since we can't actually tell the difference between the first two expressions above. It's arguable that `@macro x, y` is ambiguous and should be a syntax error, but that change would have to happen in Julia itself.

**Comment by sbromberger** [comment]
Thank you - this makes sense. The solution, I guess, is to use explicit parentheses with `compat`.

**Comment by kmsquire** [comment]
`@compat` does recurse into expressions (as you found by putting it out front).  Of course, putting it around a large chunk of code would probably be slow (but should work), so you should pick where you put it judiciously.  But in front of a function call or definition, even, should generally be okay.
