### ISSUE TITLE
Take care of the transition to AbstractFloat

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/Compat.jl#121]
Need to provide the facility to help package developers to deal with the `FloatingPoint` to `AbstractFloat` transition (https://github.com/JuliaLang/julia/pull/12162).

**Comment by lindahua** [comment]
Looks like `FloatingPoint` is not actually deprecated (still usable without warnings).

**Comment by nalimilan** [comment]
> Looks like FloatingPoint is not actually deprecated (still usable without warnings).

That's because there's no way currently to deprecate types (https://github.com/JuliaLang/julia/issues/11200).
