### ISSUE TITLE
Nullable collides with methods to convert internal storage types

### ISSUE THREAD

**Issue by AndrewGibb** [JuliaLang/Compat.jl#122]
I have some types for geometry, like this one:
```julia
immutable Point{T<:Real}
       x::T
       y::T
end
```
If I am using Compat.jl, then if I try to define a method to convert the internal storage of an instance of this type, I get a warning:
```julia
using Compat
import Base.convert
convert{T,S}(::Type{T},p::Point{S}) = Point(convert(T,p.x), convert(T,p.y))
Warning: New definition
    convert(Type{T},Point{S}) at none:1
is ambiguous with:
    convert(Type{Nullable{T}},T) at /Users/andrewg/.julia/v0.3/Compat/src/nullable.jl:24.
To fix, define
    convert(Type{Nullable{_<:Point{S}}},_<:Point{S})
before the new definition.
```
Now, I understand what the warning is instructing me to do. I don't see the ambiguity, though. And the suggested fix seems cumbersome. I haven't tested it in 0.4, but adding the extra convert definition for any method which converts internal types seems like quite an overhead. 

Please can someone help me understand what is going on here, whether it is a bug, or a feature, and whether the behaviour is expected to be the same in 0.4?

**Comment by JeffBezanson** [comment]
To change the storage type, you want to convert to Point{T}, not T. Your definition says that a Point can be converted to all other types.

**Comment by timholy** [comment]
You shouldn't declare a convert method like that; it should be
```jl
convert{T,S}(::Type{Point{T}}, p::Point{S})
```
(you can't convert a `Point{Float32}` into a `Number`, for example).

The ambiguity warning is real, because the method definition doesn't know that `T !<: Nullable`.

**Comment by AndrewGibb** [comment]
Thanks both for taking the time to refine my understanding of types, and conversion.
