### ISSUE TITLE
WARNING: unknown Compat commit 526a5f5c, metadata may be ahead of package cache

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Compat.jl#129]
I'm getting this on `Pkg.update` for Compat, and on several other package operations (e.g. `Pkg.tag`).  It seems to be due to the [0.4.5 tag](https://github.com/JuliaLang/METADATA.jl/commit/f78e480658427659ebeed0552b9c8eaa27ce3c71) referring to a dangling commit 526a5f5c4f852cb046fc8bd16def839a21f231b8.  cc: @timholy

**Comment by tkelman** [comment]
Odd, does that not get fetched? Maybe we could adjust the tag in metadata (and maybe here too) to the immediate parent commit, 053a696dcfb11b30095b54e0466fdc00079920b6

**Comment by stevengj** [comment]
Okay, I changed the metadata.  Not sure how to change the tag here.
