### ISSUE TITLE
Depwarn for chol

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/Compat.jl#157]
Ref https://github.com/JuliaLang/julia/pull/13680. @andreasnoack

**Comment by andreasnoack** [comment]
Could you elaborate here? Are there any `chol` methods 0.5 that are invalid in 0.4?

**Comment by yuyichao** [comment]
Not invalid but `chol(A, Val{:U/:L})` is deprecated on 0.5 and this is [what Compat is generating](https://github.com/JuliaLang/Compat.jl/blob/6de3fbaa99ee121153c97a12a93850aa01421903/src/Compat.jl#L387)

**Comment by andreasnoack** [comment]
So adding an upper bound on that condition should be sufficient?

**Comment by yuyichao** [comment]
> So adding an upper bound on that condition should be sufficient?

(Also in the test.)

And then use `chol()` and `ctranspose(chol())` on all versions? I think that should work.

**Comment by hayd** [comment]
Should the chol test just be removed?
