### ISSUE TITLE
@compat for @BLAS.blasfunc

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/Compat.jl#166]
BLAS.blasfunc in 0.4 is now @BLAS.blasfunc in 0.5, and this is not included in Compat.jl

**Comment by tkelman** [comment]
This isn't exported from base, how many packages are using this?

**Comment by dlfivefifty** [comment]
Probably not many.  I figured out my own solution:

```julia
if VERSION < v"0.5.0-dev"
    macro blasfunc(x)
       return :( $(BLAS.blasfunc(x) ))
    end
else
    import Base.BLAS.@blasfunc
end
```
so I'll close the issue
