### ISSUE TITLE
chksquare is now called checksquare

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Compat.jl#168]
https://github.com/JuliaLang/julia/pull/14601

**Comment by KristofferC** [comment]
I can fix it if I know how to get the build number from the PR.

Is it the same as the one in the Travis log for the PR or does it depend on when it is merged?

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/Compat.jl#developer-tips

**Comment by stevengj** [comment]
`VERSION >=  v"0.5.0-dev+9476"`

**Comment by KristofferC** [comment]
I get:

```
$ ~/.julia/v0.5/Compat/bin/version.sh 0a1a612407fd53c03593faa51cb643672893151c
0.4.0-dev+2058
```

where I used the merge commit: https://github.com/JuliaLang/julia/commit/0a1a612407fd53c03593faa51cb643672893151c

Anyway, it seems like you can't create a new binding inside a module from another module and since `chksquare` wasn't exported I'm having some troubles...

**Comment by yuyichao** [comment]
You can create new binding from another module, use `eval(module, ...)` or `module.eval(...)`.

And I believe the common pactice in `Compat` for this is to define it as `Compat.foo` instead.

**Comment by stevengj** [comment]
@KristofferC, I used the same commit and I got `+9476`, not 2058; I'm not sure why you're getting a different number.  (The 0.4 is simply wrong, since this commit is in the 0.5 tree.)

**Comment by yuyichao** [comment]
The `0.4.0` is due to https://github.com/JuliaLang/Compat.jl/issues/151

**Comment by KristofferC** [comment]
Thanks @andreasnoack
