### ISSUE TITLE
Provide `@boundscheck` macro

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/Compat.jl#182]
`@boundscheck` exists only in Julia 0.5. In Julia 0.4, it should probably be a no-op since the respective functionality does not exist.

**Comment by c42f** [comment]
Uh oh.  I thought this was as simple as adding a no-op macro, but `@boundscheck` also exists in v0.4 with a different meaning and different number of arguments.  The fix will have to go into the `@compat` macro instead I suppose.

**Comment by yuyichao** [comment]
Rewrite with `@compat` will break existing code. Probably should just define a unexported `@boundscheck` and let packages use `Compat.@boundscheck` instead.

**Comment by yuyichao** [comment]
Before that `Compat` is not expected to break anything. When the two conflict, as in this case, you should find a syntax that is closed enough to the master one but does not break existing code.

**Comment by yuyichao** [comment]
> this is what's documented in the Compat README

If this encourage people to think writing in master syntax is all what `Compat` is about, we should delete it.

Compat is about writing code that doesn't have to do version check that works without depwarn on multiple versions of julia. As a dependency of a large number of package, it should avoid breaking existing users as long as it's possible and reasonable to do. Writing in master syntax is then the preferred way to achieve this, when possible and doesn't violate the non-breaking rule.

**Comment by c42f** [comment]
Ok, the README probably needs some updating to note this subtle point (it would have saved me some time figuring out how to implement the wrong thing...)

**Comment by c42f** [comment]
I just realized that we're lucky, and we can in fact distinguish this on the syntax level, providing both forward and backward compatibility via `@compat`: the old `@boundscheck` had two arguments, but the new one has only a single argument.

I'll update the PR.

**Comment by c42f** [comment]
By the way, I can't find a single use on github so far of the old form of `@boundscheck` in 0.4 packages.  Github code search isn't great though, so I've probably missed some.

**Comment by yuyichao** [comment]
That's true. Too bad that macros can't automatically support overloading on 0.4.
