### ISSUE TITLE
String is back

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Compat.jl#193]
As of JuliaLang/julia#16058, @StefanKarpinski has restored the `String` type, replacing `ASCIIString` and `UTF8String`.   This will cause a zillion deprecation warnings everywhere, so Compat will need some glue ASAP.

`String` in Julia 0.3 was what we now call `AbstractString`, but hopefully almost everyone has upgraded their old 0.3 packages.

**Comment by stevengj** [comment]
Ah, I see we already have #192.  Thanks Stefan!

**Comment by timholy** [comment]
Closed by #197.
