### ISSUE TITLE
Broken String conversions

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Compat.jl#210]
I'm getting
```
julia> Compat.String("foo")
ERROR: TypeError: typeassert: expected AbstractString, got Tuple{ASCIIString}
 in call at /Users/stevenj/.julia/v0.4/Compat/src/Compat.jl:37
```
on Julia 0.4, apparently as a consequence of #206 (cc @quinnj).

This seems to be the source of stevengj/PyCall.jl#281

**Comment by stevengj** [comment]
Looks like the method definition should be `call(::Type{Base.ByteString},s::AbstractString...) = bytestring(s...)`

**Comment by quinnj** [comment]
Ah, I thought I had tested this [here](https://github.com/JuliaLang/Compat.jl/pull/206/files#diff-fce720c43af3c52c862fd7451c7374b8R1157), but it looks like it didn't quite connect through.

**Comment by stevengj** [comment]
Maybe you had intended to call `String` rather than `string`?
