### ISSUE TITLE
@compat get for Nullable types throws a BoundsError

### ISSUE THREAD

**Issue by BenLauwens** [JuliaLang/Compat.jl#228]
I am the maintainer of SimJulia and recently the @compat macro for getting a Nullable type in Julia v0.3 and Julia v0.4 throws a BoundsError.

I isolated the problem with following small example:

`using Compat

type Test
a :: Float64
end

type TestCompat
t :: @compat Nullable{Test}
function TestCompat()
tc = new()
tc.t = @compat Nullable{Test}()
return tc
end
end

tc = TestCompat()
@compat get(tc.t)`

In Julia v0.4 without the @compat macro everything works fine (a NullException is thrown) but with the macro I get the following error message:
ERROR: LoadError: BoundsError: attempt to access 2-element Array{Any,1}:
:get
:(tc.t)
at index [3]

**Comment by nalimilan** [comment]
Argh, looks like the new compatibility for `IOContext` (https://github.com/JuliaLang/Compat.jl/pull/212) didn't consider the one-argument version of `get`.

@timholy Any ideas?

@BenLauwens Do you really need `@compat` for `get` to work on Julia 0.3? As it's a normal function, `using Compat` should be enough.

**Comment by BenLauwens** [comment]
I removed the @compat and get works fine on Julia v0.3. The issue can be closed.
Thanks for the quick response!

Ben

**Comment by TotalVerb** [comment]
@nalimilan: Another reason not to have one-argument `get` :wink:.
