### ISSUE TITLE
Add support for Dict generator syntax.

### ISSUE THREAD

**Issue by blakejohnson** [JuliaLang/Compat.jl#231]

**Comment by yuyichao** [comment]
This is almost impossible since it requires parser change. (You can do it with a string macro though.)

**Comment by blakejohnson** [comment]
Ok, fair enough. I guess people will just have to live with the deprecation warnings for one release cycle.

**Comment by yuyichao** [comment]
It is possible to write a macro that translate the old syntax to the new syntax on newer version and it will get rid of the depwarn on 0.5. However, it's not how Compat usually works and it will likely break when the deprecation is removed.

**Comment by samoconnor** [comment]
Is there currently any way to do better that this to make a package warning-free for 0.4 and 0.5?

```julia
macro v05init()
    esc(parse("""
        begin
            SymbolDict(d::Dict) = Dict(Symbol(k) => v for (k,v) in d)
            StringDict(d::Dict) = Dict(string(k) => v for (k,v) in d)
        end
        """))
end

if VERSION < v"0.5.0-dev+4340"
    SymbolDict(d::Dict) = [Symbol(k) => v for (k,v) in d]
    StringDict(d::Dict) = [string(k) => v for (k,v) in d]
else
    @v05init()
end
```

**Comment by TotalVerb** [comment]
This should work:

```
Dict([Pair(Symbol(k) => v) for (k, v) in ((1, 2), (3, 4))])
```

**Comment by samoconnor** [comment]
The intermediate array of pairs does seem to have performance overhead.

```julia
foo(d) = Dict([Pair(Symbol(k) => v) for (k, v) in d])
bar(d) = Dict(Symbol(k) => v for (k, v) in d)

d = Dict("a" => 1, "b" => 2, "c" => 3)

println(foo(d))
println(bar(d))

test_foo() = for i = 1:100000 foo(d) end
test_bar() = for i = 1:100000 bar(d) end

@time test_foo()
@time test_bar()
```

```julia
Dict(:c=>3,:b=>2,:a=>1)
Dict(:c=>3,:b=>2,:a=>1)
  0.378140 seconds (1.71 M allocations: 123.964 MB, 50.86% gc time)
  1.603094 seconds (2.72 M allocations: 210.075 MB, 0.92% gc time)
```

It would be nice if the Compat.jl README had some instructions for how packages should maintain 0.4 compatibility without significant performance overhead in 0.5 and without a need to re-write again later when 0.4 support is dropped.

**Comment by yuyichao** [comment]
FYI, the performance difference is indeed small for small Dict but you are only benchmarking the poor performance of global variables.

**Comment by samoconnor** [comment]
Fair enough,
The difference is almost nothing without global variables:
```julia
d() = Dict(string(i) => i for  i = 1:100)
test_foo() = begin x = d(); for i = 1:100000 foo(x) end end
test_bar() = begin x = d(); for i = 1:100000 bar(x) end end
@time test_foo()
@time test_bar()
```
```julia
  2.886156 seconds (22.92 M allocations: 1.418 GB, 10.35% gc time)
  2.929766 seconds (23.92 M allocations: 1.428 GB, 2.66% gc time)
```

Maybe the depwarn message and/or the README should be updated to suggest using `Dict([Pair...`.

**Comment by stevengj** [comment]
In my packages, I've just used an explicit loop to initialize the dictionary, in order to work without warnings on 0.4 and 0.5.
