### ISSUE TITLE
Build error: `chksquare` not defined

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/Compat.jl#241]
I see this error when building Compat with a recent master checkout of Julia:

```
ERROR: LoadError: UndefVarError: chksquare not defined
```

I believe these lines cause the problem:

```
module LinAlg
    if VERSION < v"0.5.0-dev+2022"
        const checksquare = Base.LinAlg.chksquare
    else
        import Base.LinAlg.checksquare
    end
end
```

because

```
julia> VERSION
v"0.5.0-dev"
```

That is, my Julia build does not know which version it has.

**Comment by tkelman** [comment]
Building without version info completely breaks compat, best to not do it. There's an old Julia issue on this.

**Comment by eschnett** [comment]
So there should be an explicit error given in this case, not an obscure error from Compat?

**Comment by tkelman** [comment]
It's fine if you're on a release tag. Without git it's a little harder to tell whether or not that's the case.

**Comment by cortner** [comment]
I tried to narrow down a bug by checking out several commits of Julia. Unfortunately as soon as I was on a commit without release tag, this error occurred.

**Comment by tkelman** [comment]
did you set `NO_GIT` ? or are you working from source that isn't from a git clone?

**Comment by cortner** [comment]
I work from a git clone, and I did not set `NO_GIT`. Are you suggesting that I should `make NO_GIT=1 `?

**Comment by tkelman** [comment]
no, `make NO_GIT=1` is likely to break Compat. if you did build from a normal git clone, what is `Base.GIT_VERSION_INFO` ?

**Comment by cortner** [comment]
julia> Base.GIT_VERSION_INFO
Base.GitVersionInfo("cede5394b79c152829203dd9c19bf30772eb7ca1","cede539","(HEAD detached at cede539)",0,"2016-08-04 08:48 UTC",true,0,1.470300497e9)

**Comment by cortner** [comment]
julia5
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc1+0 (2016-08-04 08:48 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-apple-darwin15.6.0

**Comment by tkelman** [comment]
did you possibly make a local tag? that would modify `build_number` and/or `fork_master_distance`

**Comment by cortner** [comment]
No, I didn't create a new tag.

**Comment by cortner** [comment]
wait - I sent you the wrong information  here. When I had the `chksquare not defined` problem it was on a different commit.

**Comment by tkelman** [comment]
are you using a shallow clone? does `git fetch --unshallow` and/or `git fetch --tags` then `make clean && make` change the result of `dump(Base.GIT_VERSION_INFO)`? the missing build information is probably causing this, ref https://github.com/JuliaLang/julia/issues/15636

**Comment by quinnj** [comment]
Doesn't sound like there's anything actionable here. Anyone feel free to re-open if that's not the case.
