### ISSUE TITLE
Compat interfers with dictionary type inference

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/Compat.jl#242]
On 0.4, the Dict key-type is wrong after using Compat

```julia
julia> [Symbol(k) => v for (k,v) in Dict{Any, Any}(:x=>3)]
Dict{Symbol,Any} with 1 entry:
  :x => 3

julia> using Compat

julia> [Symbol(k) => v for (k,v) in Dict{Any, Any}(:x=>3)]
Dict{Any,Any} with 1 entry:
  :x => 3
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7258 Not really fixable.

**Comment by nalimilan** [comment]
@yuyichao But why would `using Compat` change this? Sounds like an unexpected (and undocumented) outcome.

**Comment by yuyichao** [comment]
Any method definition can change this. Type inference was just being nice about guessing `Symbol(::Any)`.

**Comment by cstjean** [comment]
It seems that the problem comes from [this line](https://github.com/JuliaLang/Compat.jl/blob/master/src/Compat.jl#L400). On Julia 0.4.5, `Symbol` is already defined, so I would guess that if we lowered the version number it would solve the issue.

**Comment by yuyichao** [comment]
No. The whole point of that line is to add method to `Symbol`.

**Comment by nalimilan** [comment]
Maybe we could add methods with more specific signatures? On 0.4, only the default `Symbol(::String)` constructor is defined: looks like it's possible to avoid messing with it.

**Comment by nalimilan** [comment]
More specifically, of the defined methods on 0.5, 0.4 already has the first. We only need to add the others:
```julia
Symbol(s::String) at coreimg.jl:52
Symbol(a::Array{UInt8,1}) at coreimg.jl:53
Symbol(s::AbstractString) at strings/basic.jl:77
Symbol(x...) at sysimg.jl:74
```

**Comment by yuyichao** [comment]
No. As I said, the whole point is to add methods to Symbol (so that it matches the signature of Symbol on 0.5). For this particular one, you can add a type assertion but the issue of adding method inferring with type inf is not fixable in Compat.

**Comment by yuyichao** [comment]
And therefore we added `Symbol(x...) at sysimg.jl:74`

**Comment by cstjean** [comment]
Replacing the definition with

`Base.Symbol(a, b, args...) = symbol(a, b, args...)`

fixes the inference bug. It's ugly and might have other consequences, so I don't know if it's appropriate...

**Comment by yuyichao** [comment]
> fixes the inference bug

It's not a bug.

> might have other consequences

It does

> so I don't know if it's appropriate...

We shouldn't do that.

And as I said,

>  For this particular one, you can add a type assertion

**Comment by cstjean** [comment]
Alright, alright. Thank you for the explanation.

**Comment by nalimilan** [comment]
It's clearly a bug, as in "not intended, nor documented, and annoying". It may or may not be fixable/workaround-able, but that's a separate question. Why do you think we shouldn't do that?

**Comment by yuyichao** [comment]
The bug is JuliaLang/julia#7258 and yes we should fix it.

**Comment by nalimilan** [comment]
We won't fix it in 0.4 though, so the bug is in Compat.

**Comment by yuyichao** [comment]
As a fact, adding any method makes type inference worse when the input is not inferenced as leaf type. If this counts as a bug in `Compat`, the only fix is to not add any methods in `Compat` at all.

**Comment by nalimilan** [comment]
What's the problem with the workaround suggested by @cstjean?

**Comment by yuyichao** [comment]
It's the wrong workaround (try `Symbol("aaa".data)`). And

> For this particular one, you can add a type assertion

**Comment by nalimilan** [comment]
Let's add a type assertion then?

**Comment by yuyichao** [comment]
That's what I'm saying. Note that you might get complaint if someone extends `symbol`, which is basically as undefined as relying on the type inference result of `Symbol(::Any)`

**Comment by nalimilan** [comment]
Extending `symbol` to return another type than `Symbol` sounds like a bad idea anyway. @cstjean Could you experiment with that solution and make a pull request?
