### ISSUE TITLE
Add Base.normalize and normalize! to Compat

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/Compat.jl#246]
It would be great to have Base.normalize and normalize! in Compat. Normalization is a very basic and common concept - having it in Compat would allow 0.4-compatible packages to use it and to provide new methods for it. It would be very natural to have `normalize!(h::StatsBase.Histogram)`, for example.

**Comment by stevengj** [comment]
A PR would be welcome.

**Comment by oschulz** [comment]
Thanks, @stevengj, I'll try to get on it soon.

**Comment by oschulz** [comment]
Thanks a lot, @ranjanan!
