### ISSUE TITLE
Base.sub is also `view` now

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/Compat.jl#251]
#235 accounted for the fact that `slice` was now deprecated in favor of `view`. But so is `sub`. The [appropriate line](https://github.com/JuliaLang/Compat.jl/blob/master/src/Compat.jl#L1286) defines a constant `view` to be `slice`. But `view` could also be `sub`. What's the right fix for this?

**Comment by timholy** [comment]
```jl
slice_04(A, 1:3, 1, 1:3) == view(A, 1:3, 1,   1:3)
  sub_04(A, 1:3, 1, 1:3) == view(A, 1:3, 1:1, 1:3)
```

**Comment by timholy** [comment]
If we want to move people in the direction of writing forward-compatible code, the only fix is documentation: tell people to rewrite their `sub` calls using `view` and the range index.

**Comment by ranjanan** [comment]
@timholy If packages on v0.4 use `sub` change it to `view`, it would then break on v0.4 right? Unless you advocate getting a v0.5 release out, changing all packages and encouraging all users to switch to v0.5.

**Comment by timholy** [comment]
No, if they're `using Compat.view`, then `view(A, 1:3, 1:1, 1:3)` will work without error.

This is because you never really needed `sub` on julia-0.4: it was effectively an alias for `slice(A, map(i->isa(i, Integer) ? (1:i) : i, inds)...)` (except for trailing dimensions).

**Comment by ranjanan** [comment]
Oh, I see. Then I guess this isn't required at all. Thank you! :)
