### ISSUE TITLE
Add linearindices and indices?

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/Compat.jl#258]
In light of the [recommendations concerning arrays with custom indices](http://docs.julialang.org/en/latest/devdocs/offset-arrays/), maybe Compat should provide `linearindices` and `indices`.

**Comment by timholy** [comment]
I can add that (those functions are pretty simple), although practically speaking I don't think anyone will be able to use arrays with custom indices on julia 0.4.

**Comment by oschulz** [comment]
@timholy Sure - I was thinking more about packages that want to keep 0.4 compatibility, but want to adopt the new style so that they'll be usable with arrays with custom indices. I guess it'll depend on how speedily the transition to 0.5 will go, and how long packages want to keep backward compatibility.

**Comment by TotalVerb** [comment]
Closed by #372.
