### ISSUE TITLE
Document minimum Compat.jl versions for features

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/Compat.jl#263]
When using Compat in packages, we require specifying a minimum version for Compat in the package's REQUIRE file. Finding this sometimes feels burdensome, and could be made a bit easier if the required Compat.jl version for each feature was included in the documentation.

**Comment by stevengj** [comment]
I agree that this would be nice.  Unfortunately, the version number is not known at the time a feature is merged, so you'd have to go back somehow at the time the package is tagged.

I guess when the feature is merged we could add `(Compat ?)` under that feature in the README, and then have a script that replaces `Compat ?` with `Compat x.y.z` and tags a version?

**Comment by ranjanan** [comment]
This may help:  To find the minimum Compat version, click on the blame icon in the README, find your function and click on the corresponding commit ID. This would then load a page that shows the minimum tagged version after this particular commit ID.

**Comment by KristofferC** [comment]
We should run a whitespace checker then: https://github.com/JuliaLang/Compat.jl/commit/12c36d71182ff15fe1c13bc51ee0384603493f59

**Comment by martinholters** [comment]
To repeat what I said in #670: The idea is to add the version information in the commit that sets the version number in `Project.toml`. I just wonder how we prevent forgetting to do so...
