### ISSUE TITLE
Iterating over tuples to produce dicts

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/Compat.jl#265]
Suppose you want to iterate over an Array of tuples, and convert it to a dictionary

`c = [(1,2), (2,1)]`

In Julia v0.4
 
You would do this:
```
julia> (Int=>Int)[a=>b for (a,b) in c]
Dict{Int64,Int64} with 2 entries:
  2 => 1
  1 => 2
```

In v0.5, this is deprecated.

`Dict{Int,Int}(a=>b for (a,b) in c)` is the right way to do it in v0.5. 

`Compat` does not support this yet, so I wondering how to include this in the package.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/Compat.jl/issues/231
