### ISSUE TITLE
WARNING: Module Compat uuid did not match cache file

### ISSUE THREAD

**Issue by zoulingnan** [JuliaLang/Compat.jl#270]
Received the error message "WARNING: Module Compat uuid did not match cache file
" when attempting to load the Optim.jl package. See full error message below. Running Julia v4.5 and IJulia notebook.

using Optim

INFO: Recompiling stale cache file /Users/zoulingnan/.julia/lib/v0.4/Calculus.ji for module Calculus.
WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.
WARNING: deserialization checks failed while attempting to load cache from /Users/zoulingnan/.julia/lib/v0.4/Calculus.ji
INFO: Precompiling module Calculus...
INFO: Recompiling stale cache file /Users/zoulingnan/.julia/lib/v0.4/Calculus.ji for module Calculus.
WARNING: Module Compat uuid did not match cache file
  This is likely because module Compat does not support  precompilation but is imported by a module that does.
LoadError: __precompile__(true) but require failed to create a precompiled cache file
while loading In[30], in expression starting on line 1

 in require at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in stale_cachefile at loading.jl:457
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in stale_cachefile at loading.jl:457
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at loading.jl:235
 [inlined code] from /Users/zoulingnan/.julia/v0.4/Requires/src/require.jl:11
 in require at /Users/zoulingnan/.julia/v0.4/Requires/src/hook.jl:17

**Comment by yuyichao** [comment]
Not a Compat issue. Should at least be gone if you try again.

**Comment by stevengj** [comment]
See JuliaLang/julia#12508
