### ISSUE TITLE
New Dict comprehension

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/Compat.jl#271]
https://github.com/JuliaLang/julia/issues/16510 deprecated
```
[i=>i*2 for i=1:2]
```
in favor of
```
Dict(i=>i*2 for i=1:2)
```

Is it possible to use compat to support both 0.4 and 0.5?

**Comment by TotalVerb** [comment]
Please see https://github.com/JuliaLang/Compat.jl/issues/231. In short, no, this is not possible, but there are workarounds.
