### ISSUE TITLE
Incorrect type when using dot syntax for broadcasting, in Julia 0.4

### ISSUE THREAD

**Issue by giordano** [JuliaLang/Compat.jl#282]
Run the following code in Julia 0.4
```julia
using Compat
x = 0:10
typeof(@compat(sin.(x)))
# => Array{Any,1}
```
while I'd expect type `Array{Float64,1}`.  This is a problem because, for example, `fft` doesn't work with `Array{Any}`.  It happens only if the argument is a named variable, `@compat(sin.(0:10))` works as expected.

**Comment by stevengj** [comment]
The type computation in `broadcast` got improved in 0.5 ...

Maybe `@compat(f.(x))` should look and see whether `f` is one of the list of built-in "vectorized" functions in 0.4 (`sin` etc. — see JuliaLang/julia#17302 for a list), and if so just call `f(x)`.

**Comment by giordano** [comment]
But in Julia 0.4 this returns the correct type:
```julia
typeof(broadcast(sin, 0.0:10.0))
# => Array{Float64,1}
x = 0.0:10.0
typeof(broadcast(sin, x))
# => Array{Float64,1}
```
May it be a problem with parsing the named variable within the macro?

**Comment by yuyichao** [comment]
This is not fixable without actually backporting a significant amount of 0.5 code back to 0.4 in Compat. The broadcast syntax compat uses the same algorithm (well, it directly uses) for comprehension so the return type is as good as that. If you make `x` a local or a `const` the problem will be gone.
