### ISSUE TITLE
.= assignment

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Compat.jl#285]
0.5 introduced `x .= y` etcetera for in-place assignment.   It would be nice if `@compat` would translate this to `copy!(x, y)` in Julia 0.4.

Note that `x[...] .= y` should become `x[...] = y`.

Similarly for `.+=` and so on.

**Comment by stevengj** [comment]
(In 0.4, `.=` is parsed as a comparison.)

**Comment by TotalVerb** [comment]
Isn't the precedence wrong?

**Comment by stevengj** [comment]
Yes. But in most practical circumstances it shouldn't matter, I think, since comparisons have lower precedence than arithmetic.

**Comment by stevengj** [comment]
And at worst, people needing 0.4 compatibility can add parents around the rhs.
