### ISSUE TITLE
Broadcasting tuples in Julia 0.5

### ISSUE THREAD

**Issue by giordano** [JuliaLang/Compat.jl#291]
Julia `master` has the ability to broadcast tuples (PR https://github.com/JuliaLang/julia/pull/16986), which is incredibly handy.  Is it possible to backport this feature to Julia 0.5 with `Compat`?

**Comment by wsshin** [comment]
I want this capability as well!

**Comment by stevengj** [comment]
I don't think it's practical (cc @pabloferz).

**Comment by pabloferz** [comment]
There's a one-liner on that PR that could be backported to 0.5

```julia
@inline broadcast{N}(f, t::NTuple{N}, ts::Vararg{NTuple{N}}) = map(f, t, ts...)
```

This would probably be enough to satisfy most of people's needs when broadcasting over tuples. Unfortunately, handling mixtures of arrays, tuples and/or scalars is too disruptive to be back-portable.

**Comment by giordano** [comment]
@pabloferz for my use case that should do the trick.

**Comment by cossio** [comment]
Has Julia 0.6 lost the ability to broadcast tuples? The following does not work
```
x = y = 0.
x, y += 2.
```
