### ISSUE TITLE
2-arg vectorized trunc doesn't work in Julia 0.5

### ISSUE THREAD

**Issue by giordano** [JuliaLang/Compat.jl#297]
In Julia 0.5
```julia
julia> trunc.(Int, 10rand(10))
ERROR: MethodError: no method matching size(::Type{Int64})
Closest candidates are:
  size{N}(::Any, ::Integer, ::Integer, ::Integer...) at abstractarray.jl:48
  size(::BitArray{1}) at bitarray.jl:39
  size(::BitArray{1}, ::Any) at bitarray.jl:43
  ...
 in broadcast_shape(::Type{T}, ::Array{Float64,1}) at ./broadcast.jl:31
 in broadcast_t(::Function, ::Type{Any}, ::Type{T}, ::Vararg{Any,N}) at ./broadcast.jl:213
 in broadcast(::Function, ::Type{T}, ::Array{Float64,1}) at ./broadcast.jl:230
```
Vectorized version of `trunc` is now preferred in master, after (probably) https://github.com/JuliaLang/julia/pull/19791.  Any chance to make it work in Julia 0.5 using `Compat.jl`?

**Comment by TotalVerb** [comment]
See also related #291. Most of the broadcasting infrastructure would be quite difficult to backport, unfortunately.

**Comment by giordano** [comment]
> See also related #291.
I know, I'm the same who reported that one ;-)

> Most of the broadcasting infrastructure would be quite difficult to backport, unfortunately.
I suspected that, but keeping compatibility in packages for both 0.5 and 0.6 is hard.  I have to choose between dropping support for 0.5 now and updating the package later.  I think I'll do the former as soon as 0.6 is out.

**Comment by stevengj** [comment]
We could define a limited number of `broadcast` and `broadcast!` methods just so that people can remove deprecations.  e.g. `broadcast(f::Function, T::Type, A::AbstractArray) = broadcast(x -> f(T, A), A)` for the `trunc`, `round`, etcetera methods.
