### ISSUE TITLE
@compat for deprecation of new broadcast functions

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/Compat.jl#308]
See https://discourse.julialang.org/t/how-to-handle-deprecations-of-new-broadcast-functions/1287/2

@stevengj proposed the following:

>  we should define the `@compat` macro to make `@compat` function `Base.broadcast(::typeof(*), ...)` turn into a `.*(...)` definition in 0.5 and 0.4.

**Comment by stevengj** [comment]
Alternatively, you can do:
```julia
if VERSION < v"0.6.0-dev.1632" # julia#17623
include_string("""
import Base: .*
.*(x::MyType, y::MyType) = ...
""")
end
```
This way, you will define your `.*` in older versions without getting a syntax-deprecation warning in 0.6.  In Julia 0.6, you normally shouldn't bother defining `Base.broadcast(::typeof(*), ...)` methods, since often they won't be called due to loop fusion anyway.

**Comment by bjarthur** [comment]
relatedly, `!(rand(Bool,3))` can be re-written as `rand(Bool,3).==false` to remain compatible with 0.5 instead of prepending a `.` as the depwarn advises

**Comment by quinnj** [comment]
I don't think this is relevant anymore (0.5 is no longer supported); feel free to re-open if that's not the case
