### ISSUE TITLE
Support `round.(Int,logspace(1,3,3))` in 0.5

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/Compat.jl#312]
`round(Int,logspace(1,3,3)))` has been deprecated in 0.6, but in 0.5 the broadcast version throws an error:
```julia
julia> round.(Int,logspace(1,3,3))
ERROR: MethodError: no method matching size(::Type{Int64})
Closest candidates are:
  size{N}(::Any, ::Integer, ::Integer, ::Integer...) at abstractarray.jl:48
  size(::BitArray{1}) at bitarray.jl:39
  size(::BitArray{1}, ::Any) at bitarray.jl:43
  ...
 in broadcast_shape(::Type{T}, ::Array{Float64,1}) at ./broadcast.jl:31
 in broadcast_t(::Function, ::Type{Any}, ::Type{T}, ::Vararg{Any,N}) at ./broadcast.jl:213
 in broadcast(::Function, ::Type{T}, ::Array{Float64,1}) at ./broadcast.jl:230
```

**Comment by ararslan** [comment]
Seems weird to backport a deprecated feature to a version where it didn't work at all...

**Comment by dlfivefifty** [comment]
`round(Int,logspace(1,3,3)))` is deprecated in favour of `round.(Int,logspace(1,3,3)))`.

**Comment by yuyichao** [comment]
For 0.5, use `round.([Int], logspace(1, 3, 3))`. Getting the original version to work on 0.5 with Compat is actually much harder than getting it work on 0.4.

**Comment by stevengj** [comment]
Or `map(x -> round(Int, x), array)`.

**Comment by yuyichao** [comment]
Or comprehension, that's what the broadcast syntax is lowered to on 0.4.
