### ISSUE TITLE
linspace tests fail on master

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/Compat.jl#315]
Probably because of https://github.com/JuliaLang/julia/pull/18777. E.g.
```jl
julia> u=eps(zero(Float32));

julia> [Compat.linspace(-u,u,4);][3] == 0
false
```

**Comment by timholy** [comment]
Yes, that test was one of the (few) casualties of the rewrite. It was advertised, see

> I was also able to restore some of the tests that I had ditched in the original implementation of this PR. The only tests that I weakened were for cases where step underflows.

**Comment by andreasnoack** [comment]
I guess we should just remove the tests here as well.
