### ISSUE TITLE
@compat struct?

### ISSUE THREAD

**Issue by richardreeve** [JuliaLang/Compat.jl#339]
Is there some reason why `struct` (and `mutable struct`) can't have an at-compat macro so it works under 0.5? As it is I seem to either have to get a deprecation under 0.6 for using `immutable`, or have the code not work under 0.6...

**Comment by KristofferC** [comment]
There is no deprecation warning of `immutable` on 0.6?

**Comment by yuyichao** [comment]
This can't be done since it's a parser change.

**Comment by richardreeve** [comment]
Sorry, yes - I managed to forget that while I was writing this. However, I'd like to switch properly to 0.6 and I understand that `struct` and `mutable struct` are the "future", so it would be good to fix them while I fix the `abstract` to `abstract type ... end` issues, and the inner constructor issue (see #332).

**Comment by stevengj** [comment]
For now, if you want to maintain compatibility with 0.5, the right thing is probably just to continue to use `immutable` and `type`, which don't have deprecation warnings for precisely this reason.

**Comment by richardreeve** [comment]
Okay, fair enough - thanks.

**Comment by rfourquet** [comment]
`immutable`/`type` are deprecated now, won't there be any solution to maintain compatibility with 0.5?

**Comment by martinholters** [comment]
Ref. #338.
