### ISSUE TITLE
support for key=val arguments in Base.@test

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/Compat.jl#340]
v0.6 allows `key=val` [forms that follow](http://docs.julialang.org/en/latest/stdlib/test.html#Base.Test.@test) the first argument of `Base.@test`, which leads to neat syntax like
```julia
@test a ≈ b atol=eps()
```
I wonder if `@compat` could support using this on `v0.5`.

**Comment by TotalVerb** [comment]
In general, maybe a `Compat.Test` package would be useful for other reasons too (e.g. testsets on v0.4, which Compat still supports, or the fix for broken test sets on v0.5.)

**Comment by yuyichao** [comment]
No, those already have their own packages. https://github.com/JuliaCI/BaseTestNext.jl https://github.com/JuliaCI/BaseTestDeprecated.jl

**Comment by TotalVerb** [comment]
Then this `key=val` syntax should also go to `BaseTestNext.jl`.

**Comment by yuyichao** [comment]
That doesn't solve the issue on 0.5

**Comment by TotalVerb** [comment]
There is no way to "solve" this issue without replacing the `@test` macro, and if we do that, since Compat still supports 0.4, we should also backport it to 0.4.

**Comment by yuyichao** [comment]
> There is no way to "solve" this issue without replacing the `@test` macro

Not true. With with or without `@compat` this can be implemented on 0.5 without replacing the original `@test`. I'm not saying the BaseTestNext version doesn't need change but that's unrelated to backport this to 0.5......

**Comment by TotalVerb** [comment]
It makes more sense to me to have the new `Base.Test` features uniformly in one place, `BaseTestNext`, than to have some features (e.g. `@test_broken`) in `BaseTestNext` and some (e.g. `@test`) in `@compat`. Having `@test` refer to `Compat.@test` and `@test_broken` to `BaseTestNext.@test_broken` would be very confusing.

**Comment by yuyichao** [comment]
Just to be clear. BaseTestNext should **NOT** be used on 0.5.

**Comment by TotalVerb** [comment]
Why not? Since packages can't have conditional dependencies by version, doesn't it make more sense to have `BaseTestNext` just import and reexport the necessary macros and functions from `Base.Test`?

**Comment by yuyichao** [comment]
1. It's not implemented that way.
2. That's why `BaseTestNext` is installable on 0.5+
3. It'll still mean that any fix in `BaseTestNext` is independent of this issue on 0.5
4. (3) is especially true since there's no reason to add `BaseTestNext` dependency for a 0.5 package.

**Comment by quinnj** [comment]
I don't think this is relevant anymore; feel free to re-open if that's not the case
