### ISSUE TITLE
parametric outer constructers with where clause

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/Compat.jl#356]
is there a way to make the following work for 0.5?  thanks.

```
julia> type Foo{T}
         a
         b
       end

julia> Foo{T}() where T<:Int = Foo{T}(1,1)

julia> Foo{Int}()
Foo{Int64}(1, 1)
```

 https://github.com/JuliaLang/Compat.jl/issues/349 https://github.com/JuliaLang/Compat.jl/issues/332

**Comment by yuyichao** [comment]
`(::Type{Foo{T}}){T<:Int}()`. This is not a compat issue, please use discourse for questions.
