### ISSUE TITLE
Drop 0.4 support?

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/Compat.jl#361]
I think it would be fairly unusual for packages to be targeting 0.4, 0.5, 0.6, and 0.7 simultaneously. Is it time to drop 0.4 support?

**Comment by martinholters** [comment]
Let's wait until METADATA closes for 0.4. (I know it is rather unlikely that a package still supporting 0.4 will depend on anything added to Compat between now and METADATA closing for 0.4, but why the rush?)
