### ISSUE TITLE
README->version via git blame no longer works?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/Compat.jl#367]
The instructions at the bottom of the README don't seem to be valid anymore...did GitHub remove info from either the "blame" page or the commit page? Or am I just being blind?

If this really is removed, then we need to find an alternative.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/Compat.jl/blame/master/README.md still works for me?

We do need a better document for the versions instead though. The blame one isn't very reliable anyway...

**Comment by timholy** [comment]
But when I click on the link associated with a particular change, I don't get the range of released versions anymore. Do you?

**Comment by yuyichao** [comment]
![spectacle x10999](https://user-images.githubusercontent.com/712232/27142104-1f6dc148-50f8-11e7-8396-64aa1a713063.png)
?

Which commit did you use? Is that actually in a tag?

**Comment by timholy** [comment]
https://github.com/JuliaLang/Compat.jl/commit/3866f8b9c43a9c5a4b99bb2f6133340eaa1bbce7 which comes from clicking on the description link from the blame page. Here's what I see from that page:
![image](https://user-images.githubusercontent.com/1525481/27142369-721f371c-50f0-11e7-9113-759530ef1ed1.png)

**Comment by timholy** [comment]
I see
![image](https://user-images.githubusercontent.com/1525481/27142423-972bc00c-50f0-11e7-98f8-f6ee0e356e47.png)

**Comment by timholy** [comment]
Using Firefox in case that matters.

**Comment by yuyichao** [comment]
Hmmm, the same for me on that commit on chromium. Looks like a @github issue.

P.S. IIRC that commit is on 0.18.0.

**Comment by yuyichao** [comment]
It seems that the release and branch including the commit is no longer shown. Only the tagged commit shows the particular tag(s) on that commit....

**Comment by Keno** [comment]
Send an email to github to complain.

**Comment by timholy** [comment]
Sent.

**Comment by timholy** [comment]
Fixed by the very nice people at GitHub (CC @shawnajean).
