### ISSUE TITLE
Add support for Core.include

### ISSUE THREAD

**Issue by musm** [JuliaLang/Compat.jl#370]
Would it be possible to also add support for  ` Base.include` https://github.com/JuliaLang/julia/blob/3c3ced4153cdc2c75319b41155c38ad1f2545fc2/base/boot.jl#L233
i.e. include accepting a module in the first argument

**Comment by stevengj** [comment]
We normally don't add Compat support for undocumented Julia internals...

**Comment by stevengj** [comment]
Changing the title as I think you mean `Core.include`, not `Base.include`.

The second argument was added in JuliaLang/julia#22064.  Before that PR, the internal `jl_load` functions themselves did not take a module argument, so it would be hard to implement this in Compat … I guess we could parse the file one expression at a time and call `eval` with the desired module argument.

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0.
