### ISSUE TITLE
Support 0.7-style Sys.is<os> rather than is_<os>

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/Compat.jl#378]
I'm not sure how best to do this, since it involves a Base module that as far as I know has been in every version, unlike Iterators. For reference, this was introduced in 0.7.0-DEV.914.

**Comment by ararslan** [comment]
I'm not sure how legit it is to do this, but we could do
```julia
if VERSION < v"0.7.0-DEV.914"
    eval(Base.Sys, :(const iswindows = is_windows))
    # likewise for the others
end
```
Or we could just parse out what we need from `@compat Sys.iswindows()` and rewrite it to `is_windows()` for earlier versions, though that's a bit inconvenient from a usage perspective.

**Comment by ararslan** [comment]
Presumably we'd also want to deprecate `Compat.is_windows` et al.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/Compat.jl/blob/c3e15e9601baebda369fa502152112a7a51d9c67/src/Compat.jl#L656

**Comment by yuyichao** [comment]
And `Compat.is_windows` etc should not be deprecated, not on old julia versions and not needed on 0.7. The test for it should be removed or disabled on 0.7.
