### ISSUE TITLE
Add support DomainError constructors that ignore  inputs

### ISSUE THREAD

**Issue by musm** [JuliaLang/Compat.jl#391]
@tkelman  comment in https://github.com/JuliaMath/SpecialFunctions.jl/pull/39#issuecomment-320432419

> May want to actually make use of the new DomainError feature? Maybe Compat could support 1 and 2-arg DomainError constructors that ignore the inputs. Hopefully that wouldn't have a performance cost on 0.6 and earlier.

**Comment by timholy** [comment]
Should also do `InexactError` and `OverflowError` in the same PR. The latter is [still pending](https://github.com/JuliaLang/julia/pull/22761), my first priority will be to get that merged.
