### ISSUE TITLE
map(Int, array) works in 0.4, not in 0.3

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/Compat.jl#44]
```
a = [true false; false true]
```

v0.3:

```
julia> using Compat

julia> map(Int,a)
ERROR: type cannot be constructed
 in map at abstractarray.jl:1328
```

v0.4: 
```
julia> map(Int,a)
2x2 Array{Int64,2}:
 1  0
 0  1
```

**Comment by jiahao** [comment]
I'm not sure how Compat can help. Call constructors are one of the major new features defining 0.4.

**Comment by sbromberger** [comment]
Is there any way we can define this in 0.3 to be int(array)? That way we don't need to keep the deprecated `int()` function in 0.4 code.

**Comment by sbromberger** [comment]
Even better, David P Sanders (https://groups.google.com/d/msg/julia-users/4pZMutzwa_s/TFimmGZFgQwJ) showed that the 0.3 equivalent of `map(Int, a)` is simply `map(int, a)`. Couldn't this be implemented via Compat?

**Comment by jakebolewski** [comment]
For numeric types you can now do `@compat(map(Int, x))` which is rewritten into the former vectorized form `int(x)`.
