### ISSUE TITLE
Missing static?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/Compat.jl#454]
I'm reviewing the diff from the METADATA PR:

https://github.com/JuliaLang/Compat.jl/compare/50c6b364e3d4255c50e7eb66e7dbd9fceea07302...36d879c25cf9ad4d451e5f1e13c73f16a79443ec#diff-f34b50ad70663b5a85fd643930f44ec4R773

Should that not be made static as well?

**Comment by quinnj** [comment]
The link doesn't seem to point to anywhere anymore; what was the definition exactly?

**Comment by ChrisRackauckas** [comment]
Odd. I forget the exact defintion, but it was an `if VERSION < v"..."` which wasn't `@static if`'d like all of the others.

**Comment by quinnj** [comment]
typically it shouldn't matter unless it's truly a syntactic/parsing-related compat issue where we need to not even parse/evaluate on an unsupported version. Feel free to re-open if it comes to you.
