### ISSUE TITLE
Support IdDict?

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/Compat.jl#464]
ObjectIdDict aquired type parameters and was renamed to `IdDict{K,V}`.  The old `ObjectIdDict` is equivalent to `IdDict{Any,Any}`.  Is there a way to support this in Compat?  I couldn't think of a way.

**Comment by fredrikekre** [comment]
I thought about this too but decided to go with https://github.com/fredrikekre/Documenter.jl/blob/f7c1ca231b1baa8e12550d6e566002a9708085b2/src/Documenter.jl#L22-L26 locally for now.

**Comment by martinholters** [comment]
We could have `@compat IdDict{Any,Any}` translate to `ObjectIdDict` on older Julia. That's probably the best we can do?

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0.
