### ISSUE TITLE
Add `Matrix(I, n, m)` method

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/Compat.jl#468]
In Julia v0.7 you don't need to specify the eltype of the matrix - it is inferred from the `UniformScaling{T}` input. Compat has only defined the `Matrix{T}(::UniformScaling, n, m)` method.

```
# Julia v0.6.2
julia> using Compat

julia> Matrix(I, 4, 4)
ERROR: MethodError: no method matching Array{T,2} where T(::UniformScaling{Int64}, ::Int64, ::Int64)
Closest candidates are:
  Array{T,2} where T(::Compat.Uninitialized, ::Any...) at string:5
  Array{T,2} where T(::Integer, ::Integer) at sysimg.jl:105

julia> Matrix{Float64}(I, 4, 4)
4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0
```

**Comment by fredrikekre** [comment]
#438

**Comment by andyferris** [comment]
Well we can't do much in `Compat` about a breaking change to the element type of `I` (we could define `Compat.I` I suppose).

The usage I was intending were things like `Matrix(4.0*I, 4, 4)`. I changed these to `Matrix{Float64}(4*I, 4, 4)` which works on v0.6 (with Compat) and v0.7.
