### ISSUE TITLE
Passing NULL pointers to ccall

### ISSUE THREAD

**Issue by dancasimiro** [JuliaLang/Compat.jl#48]
Julia got stricter about passing a NULL pointer through ccall in v0.4. I think that it was this JuliaLang/julia@3387e7776b65c80d7f28632a471cfd79e5d54844 to Julia, but I'm not sure. I had to update the WAV.jl package with this: dancasimiro/wav.jl@7ed82cb0507c7489a33e16f926e473130a7a0ab6 to fix WAV.jl on 
```
julia> versioninfo()
Julia Version 0.4.0-dev+3723
Commit b80f7db* (2015-03-08 05:30 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.1.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

The code works in v0.4, without printing any deprecation warnings. However, I get the following error on v0.3.6:
```
julia> WAV.wavplay(data, fs)
ERROR: type: AudioQueueEnqueueBuffer: in ccall argument 4, expected Ptr{None}, got Nothing
 in AudioQueueEnqueueBuffer at /Users/daniel.casimiro/.julia/v0.4/WAV/src/wavplay-audioqueue.jl:175
 in enqueueBuffer at /Users/daniel.casimiro/.julia/v0.4/WAV/src/wavplay-audioqueue.jl:192
 in wavplay at /Users/daniel.casimiro/.julia/v0.4/WAV/src/wavplay-audioqueue.jl:361

julia> versioninfo()
Julia Version 0.3.6
Commit 0c24dca* (2015-02-17 22:12 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment]
I think you can pass `C_NULL` in both 0.3 and 0.4, no?   (What doesn't work anymore is passing `0`.)  In which case, nothing is needed in Compat.

**Comment by kmsquire** [comment]
One problem I ran into for v0.3 is that `C_NULL` was a `Ptr{Void}`, but if I specified a more specific pointer type in the ccall signature, it isn't automatically converted.

**Comment by stevengj** [comment]
@kmsquire, are you sure?  I just tried Julia 0.3.2, and both `convert` and `cconvert` are defined for pointer conversions.

**Comment by kmsquire** [comment]
@stevengj, I swear I ran into this in VideoIO code at one point, but looked, and I seem to have removed my workarounds, so it's likely I was just doing something wrong in the first place.  Sorry for any misinformation!

**Comment by dancasimiro** [comment]
```C_NULL``` works. Thanks!
