### ISSUE TITLE
Compat for deprecated lowercase conversions?

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/Compat.jl#49]
With JuliaLang/julia#10452 merged, we could use some `Compat` support for `float64`, `int32`, etc.

**Comment by tkelman** [comment]
You mean the reverse, right? Emulating call overloading `Float64(x)`, `Int32(x)`, etc via the `@compat` macro?

**Comment by jiahao** [comment]
It does depend on how you read the preposition, but yes.
