### ISSUE TITLE
Replace deprecated A_mul_B! to mul!

### ISSUE THREAD

**Issue by alkorang** [JuliaLang/Compat.jl#509]
`A_mul_B!` has been deprecated and replaced to `mul!`.
[deprecated A_mul_B!](https://github.com/JuliaLang/julia/blob/029fb723c08530d6a9fadb61cb84f5c1b6cc3402/stdlib/LinearAlgebra/src/deprecated.jl#L680)

**Comment by garrison** [comment]
`lmul!` and `rmul!` will also be useful here.

**Comment by alkorang** [comment]
That's right. I only mentioned `A_mul_B!`, but actually there are a lot more.

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0.
