### ISSUE TITLE
@compat round error on Julia v0.3.6  

### ISSUE THREAD

**Issue by weijianzhang** [JuliaLang/Compat.jl#51]
Hi, 

I am using Julia v0.3.6. Here are the error messages:

```julia
julia> using Compat

julia> @compat round(Integer, 5.3)
ERROR: `round` has no method matching round(::Type{Integer}, ::Float64)

julia> @compat round(Int, 5.3)
ERROR: `round` has no method matching round(::Type{Int64}, ::Float64)
```

Did I do something wrong?

**Comment by jiahao** [comment]
Works for me. What version of Compat are you using? (Also, the `@compat` macro is not necessary.)

**Comment by weijianzhang** [comment]
Sorry, my bad. Just noticed I had the Compat package pinned to 0.2.1. 
Just reinstall it. It works fine now.
