### ISSUE TITLE
`length(::CartesianIndices)` errors due to overwritten `prod()`

### ISSUE THREAD

**Issue by rdeits** [JuliaLang/Compat.jl#523]
Using Compat.jl master:

```julia
julia> using Compat

julia> c = CartesianIndices((1:2,))
2-element Compat.CartesianIndices{1,Tuple{UnitRange{Int64}}}:
 CartesianIndex{1}((1,))
 CartesianIndex{1}((2,))

julia> length(c)
ERROR: MethodError: no method matching prod(::Tuple{Int64})
You may have intended to import Base.prod
Closest candidates are:
  prod(::Any, ::AbstractArray; dims) at /home/rdeits/.julia/v0.6/Compat/src/Compat.jl:1723
  prod(::AbstractArray; dims) at /home/rdeits/.julia/v0.6/Compat/src/Compat.jl:1717
Stacktrace:
 [1] length(::Compat.CartesianIndices{1,Tuple{UnitRange{Int64}}}) at /home/rdeits/.julia/v0.6/Compat/src/Compat.jl:1288
```

The problem is here: https://github.com/JuliaLang/Compat.jl/blob/294f171d42a4aefa7dbc790fd9db88362837ad28/src/Compat.jl#L1715
where a new `prod()` function is declared, rather than extending `Base.prod`, and then that overwritten version is called here: https://github.com/JuliaLang/Compat.jl/blob/294f171d42a4aefa7dbc790fd9db88362837ad28/src/Compat.jl#L1288 instead of Base.prod. 

Is it intentional that Compat is overwriting rather than extending those functions?

**Comment by martinholters** [comment]
Yes, it's intentional. The call to `prod` needs to be prefixed with `Base`. Missed in #518, sorry. (Seems like we're missing a test for that` length` method.)
