### ISSUE TITLE
`replace` and `replace!`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/Compat.jl#526]
This is a reminder to add these very useful functions.  I haven't looked around the 0.6 `Base` enough to know off the top of my head what these should be replaced with in 0.6, pun intended.

I can do this, but I won't get around to it until the weekend at the earliest.

**Comment by stevengj** [comment]
Note that 0.6 already has `replace`. And we already added Compat for an API change in #445. Could you be more specific about what methods are missing?

**Comment by ExpandingMan** [comment]
Sorry, so basically the string methods exist in 0.6, but all the more general container methods are missing.

So, at least the following:
```
# 12 methods for generic function "replace":
[1] replace(a::Union{Function, Type}, b::Pair; count) in Base at set.jl:486
[2] replace(a::Union{Function, Type}, b::Pair, c::Pair; count) in Base at set.jl:487
[8] replace(A, old_new::Pair...; count) in Base at set.jl:426
```
and all methods of `replace!`.

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0.
