### ISSUE TITLE
Add DEPOT_PATH?

### ISSUE THREAD

**Issue by tlnagy** [JuliaLang/Compat.jl#527]
`LOAD_CACHE_PATH` was deleted in https://github.com/JuliaLang/julia/pull/26165, but the replacement `DEPOT_PATH` isn't available in Compat yet.

We use this in `Compose.jl` to provide a helpful message to users when when `Cairo.jl` is not installed. https://github.com/GiovineItalia/Compose.jl/blob/bda806864f03acd8b0c290b23983297bf87c65ba/src/Compose.jl#L154-L155

**Comment by stevengj** [comment]
I don't think DEPOT_PATH is equivalent to LOAD_CACHE_PATH…

**Comment by stevengj** [comment]
Sounds good to add to Compat.

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0.
