### ISSUE TITLE
Wrong `IteratorSize` for `pairs(::IndexCartesian, ...)`

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/Compat.jl#540]
On Julia master:
```julia
julia> Base.IteratorSize(pairs(IndexCartesian(), zeros(2,2)))
Base.HasShape{2}()
```
On Julia 0.6 with Compat:
```julia
julia> Compat.IteratorSize(Compat.pairs(IndexCartesian(), zeros(2,2)))
Base.HasLength()
```

We implicitly test for the latter behavior, making our tests fail on 0.7. We probably want to do
```diff
diff --git a/test/runtests.jl b/test/runtests.jl
index 4201f5fe..05bbf174 100644
--- a/test/runtests.jl
+++ b/test/runtests.jl
@@ -778,9 +778,9 @@ let
     A14 = [11 13; 12 14]
     R = CartesianIndices(Compat.axes(A14))
     @test [a for (a,b) in pairs(IndexLinear(),    A14)] == [1,2,3,4]
-    @test [a for (a,b) in pairs(IndexCartesian(), A14)] == vec(collect(R))
+    @test [a for (a,b) in pairs(IndexCartesian(), A14)] == collect(R)
     @test [b for (a,b) in pairs(IndexLinear(),    A14)] == [11,12,13,14]
-    @test [b for (a,b) in pairs(IndexCartesian(), A14)] == [11,12,13,14]
+    @test [b for (a,b) in pairs(IndexCartesian(), A14)] == [11 13; 12 14]
 end
 
 # Val(x)
```
But that requires fixing the result of `pairs`, which currently relies on `IndexValue` on 0.6. Should we replace the whole implementation https://github.com/JuliaLang/Compat.jl/blob/9ae12616a525b6d331884555269f0d538b99e3b0/src/Compat.jl#L574-L614 with the current one from Base?

**Comment by nalimilan** [comment]
I'm afraid we cannot change the existing implementation on 0.6 or it could break packages that rely on it. So maybe just make the test conditional on the Julia version? Anyway it's a relatively obscure method.

BTW, https://github.com/JuliaLang/julia/pull/27038 will change this test again.

**Comment by martinholters** [comment]
I really don't know enough about the details to make a call on how to proceed here, but...

> So maybe just make the test conditional on the Julia version?

That sounds like the opposite of what Compat should do. If the best we can do is that `pairs(IndexCartesian(), ...)` has slightly different behavior depending on Julia version, then I guess we should make the test independent of the difference and add a brief warning to the README.

**Comment by nalimilan** [comment]
In practice it would be equivalent whether we test specific behaviors on each version, or whether we call `vec` before checking the result on all versions. I guess we can add a warning but that's really not a common method so not a big deal.

**Comment by martinholters** [comment]
So just add `vec` on both sides of the `==` and live with the slight difference across Julia versions? Would be OK with me.

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0 and removed the code in question.
