### ISSUE TITLE
Fate of qr

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/Compat.jl#556]
From our README:

* `Compat.qr` takes `pivot` as a `Val` _instance_ and keyword argument `full` ([#22475], [#24279]).

And we have these tests:

https://github.com/JuliaLang/Compat.jl/blob/2a822219a157b7fe0f45c6549fe4020c342ac29f/test/runtests.jl#L1676-L1695

But in JuliaLang/julia#27212 the `LinearAlgebra` API has been changed, `qr` doesn't take a `full` (`thin` in 0.6) keyword anymore, making these tests fail. Instead, both the "full" and the "thin" representation can be obtained from the returned object.

Ideally, we provide a `qr` that does the same and deprecate the current method to that. But I have no idea whether that is feasible.

**Comment by Sacha0** [comment]
I err to agreeing with `@fredrikekre` in https://github.com/JuliaLang/Compat.jl/pull/555#issuecomment-391626555, i.e. simply versioning the tests and moving on. Best!
