### ISSUE TITLE
make `@doc` a no-op if Docile can't be loaded?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Compat.jl#56]
I've had some trouble getting Docile installed on some older versions of Julia. Since Docile provides no necessary functionality for most packages that "depend" on it, it would be nice to make this an optional dependency instead: if the Docile package cannot be loaded then just ignore `@doc` macros.

**Comment by spencerlyon2** [comment]
:+1:

**Comment by hayd** [comment]
It would also be great to do something similar for `doc"..."` (Note `doc_str` can include LaTeX so this should not do any interpolation). That way the following syntax should work (but be harmless if Docs/Docile are not available):

```
@compat doc"..."
function foo() end
```

cc @one-more-minute @MichaelHatherly

**Comment by MichaelHatherly** [comment]
Something like

```jl
module Foo

VERSION < v"0.4-dev" && using Docile

doc"""
$$f(x) = x^2$$
"""
function foo(x)
    x
end

end # module
```

should be working fine in 0.3/0.4 at the moment. (Remembering to ``using Lexicon`` in 0.3 at the REPL as well.)

> can include LaTeX so this should not do any interpolation

``Base.doc_str""`` does a bit of a hybrid approach rather than just disallowing interpolation as ``Docile.doc_str""`` does. See

```
julia> doc"$x = y$"
x = y

julia> doc"$x = y$ $t(1)"
ERROR: UndefVarError: t not defined
``` 

A ``@compat`` in front of a bare docstring stops the parser from transforming it into a call to ``Base.@doc`` so I'm not sure if something like that would be workable. See

```
julia> text = """
       module Foo
       @compat doc"..."
       f(x) = x
       end
       """
"module Foo\n@compat doc\"...\"\nf(x) = x\nend\n"

julia> parse(text)
:(module Foo
    eval(x) = begin  # none, line 1:
            top(Core).eval(Foo,x)
        end
    eval(m,x) = begin  # none, line 1:
            top(Core).eval(m,x)
        end # line 2:
    @compat @doc_str("...") # line 3:
    f(x) = begin  # none, line 3:
            x
        end
    end)
```

**Comment by hayd** [comment]
If the above were in Compat.jl then doing `using Compat` would ensure that `doc_str` would be defined, so I think we'd be in business (no need for `@compat doc".."`).

I guess the question is should Docile be a dependency? If it's not installed doc".." will just be thrown away, so no big deal. ?

**Comment by MichaelHatherly** [comment]
> If the above were in Compat.jl

Yes, just exported defs such as

```jl
macro doc_str(text) text end
macro doc_mstr(text) text end
```

should be enough. Docile doesn't really need to be imported into a module to still be able to document it, so having it as a Compat.jl dep seems unnecessary.

**Comment by hayd** [comment]
Any thoughts what `@doc` could be defined as? This seems too naive:
```
macro doc(ex) :($(esc(ex.args[end]))) end
```

**Comment by MichaelHatherly** [comment]
```jl
macro doc(ex) esc(ex.args[end]) end
```

should work fine for the ``->``-style syntax. If you want the 2-arg version of ``@doc`` to work, which probably doesn't really need support outside of ``base/docs/basedocs.jl``, then it would need a little more work.
