### ISSUE TITLE
scoping/escaping bug in @cfunction

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Compat.jl#565]
The `Compat.@cfunction` macro (#553) seems to have an escaping or scoping bug of some kind that prevents it from being used in a function.  For example:
```jl
julia> using Compat

julia> foo(x) = x+1
foo (generic function with 1 method)

julia> bar() = @cfunction(foo, Int, (Int,))
bar (generic function with 1 method)

julia> bar()
ERROR: UndefVarError: foo not defined
Stacktrace:
 [1] bar() at ./REPL[3]:1

julia> baz() = cfunction(foo, Int, Tuple{Int})
baz (generic function with 1 method)

julia> baz()
Ptr{Void} @0x0000000121a79f50
```
cc @ararslan .

**Comment by stevengj** [comment]
Looks like the other arguments need to be escaped too: `:(Base.cfunction($(esc(f)), $(esc(rt)), Tuple{$(esc(tup))...}))`

**Comment by yuyichao** [comment]
`esc` is needed for **ALL** user inputs, doesn't matter if they are written to or not. Unescaped symbols will always be interpreted as belonging to the scope of the macro. Ones that are written to will be interpreted as local variable of the macro and symbols that are not written to will be interpreted as global variable in the scope of the macro.
