### ISSUE TITLE
Compat should only bump minor version for breaking releaes

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Compat.jl#576]
According to https://github.com/JuliaLang/Pkg.jl/pull/370#issuecomment-396961808 which is yet to be formalized, for pre 1.0 packages, bumping the minor version is a breaking change (similar to for Julia). It seems Compat now bumps minor version for feature additions that are non-breaking. This should only be done when the package is post 1.0.

The reason for caring is that specifying the bounds will in Pkg3 look something like https://julialang.org/Pkg.jl/latest/#Version-specifier-format-1 and if one specifies the compatibility with Compat as `0.68` that will mean the range `[0.68.0, 0.69.0)`. So `0.68` is not compatible with `0.69`.

Another way out, instead of changing how versions are bumped, is just to tag 1.0 for Compat and continue bumping minor versions for features and use patches for bugfixes.

On the other hand, people might not even use Compat for 0.7 so it might not matter much.

cc @StefanKarpinski

**Comment by StefanKarpinski** [comment]
I think that if Compat persists post 1.0, it should use major versions (`x.0.0`) for breaking changes and minor versions (`x.y.0`) for non-breaking changes. That would make `^x.0` behave as desired.

**Comment by ChrisRackauckas** [comment]
This can be closed?
