### ISSUE TITLE
Dates compat?

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/Compat.jl#58]
Is it possible to do something like:

```julia
@compat using Dates
```
and have it expand to something like:
```julia
if VERSION < v"0.4"
    using Dates
else
    using Base.Dates
end
```
?

**Comment by hayd** [comment]
similarly for Markdown.

*The annoying packaging part is what do you include in your REQUIRES file, I think at the moment you have to include Dates and so in 0.4 you'll have two Dates kicking around... It would be nice if you could somehow make Dates itself a no-op if you had Base.Dates.*

**Comment by milktrader** [comment]
+1 for this feature. Would clean up many of my modules!
