### ISSUE TITLE
Support `for outer i = ...`

### ISSUE THREAD

**Issue by pochoi** [JuliaLang/Compat.jl#595]
I am wondering if a macro for the compatibility of new syntax `for outer i = ...` would be useful.

 `for outer i = ...` is introduced in Julia 0.7 https://github.com/JuliaLang/julia/issues/22314 in order to distinguish the different behaviours of `for i = ...` between 0.7 and older versions. 

Julia in older versions gives error `ERROR: syntax: invalid iteration specification` for this new syntax.

**Comment by martinholters** [comment]
I agree this would be nice to have, but the `for outer ...` fails at the parser level (on 0.6), so a macro never gets to see it. One could conceivably introduce a `@for_outer` macro so that
```julia
@for_outer i = ... begin
    ...
end
```
does the expected. But I'm not sure it's worth it.

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0.
