### ISSUE TITLE
Tridiagonal{T} => Tridiagonal{T,V} in 0.7

### ISSUE THREAD

**Issue by hessammehr** [JuliaLang/Compat.jl#597]
My little bit of research led me here - hope I've come to the right place.

As of [this commit](https://github.com/JuliaLang/julia/commit/1dedf5053487d8b0a65556f39b1e1fbc42548b41), Tridiagonal matrices are parameterized on their wrapped vector type; that is

```julia
Tridiagonal{T} where T
```
becomes
```julia
Tridiagonal{T,V} where {T,V<:AbstractVector{T}}
```

At the moment, both Interpolations.jl and AxisAlgorithms.jl are broken because they use `Tridiagonal{T}`. Could we add a shim to Compat to fix this? Say

```julia
const Tridiagonal{T} = Tridiagonal{T,V} where {T,V<:AbstractVector{T}}
```

**Comment by hessammehr** [comment]
I should add that AxisAlgorithms.jl has dropped their Compat dependency, but adding that back would seems easier than breaking the library for 0.6 or adding the shim directly to their code.

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0.
