### ISSUE TITLE
Implement @isdefined

### ISSUE THREAD

**Issue by jekbradbury** [JuliaLang/Compat.jl#609]
`isdefined(::Symbol)` was deprecated to the newly-implemented `@isdefined` in 0.7 as a part of https://github.com/JuliaLang/julia/pull/22064. PR coming.

**Comment by yuyichao** [comment]
If you do, make sure you read through #402. If you haven't it most likely that your implementation is wrong.

**Comment by jekbradbury** [comment]
Welp, missed this https://github.com/JuliaLang/Compat.jl/pull/402. Closing in favor of trying to figure out what's going on there.
