### ISSUE TITLE
Pair() for 0.3?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/Compat.jl#61]
Is `Pair` a good candidate for inclusion into `Compat`, or is this a request better made to the 0.3 maintainers (to cherrypick it)?

**Comment by hayd** [comment]
IMO yes... is this tricky to do? [Pair definition](https://github.com/JuliaLang/julia/blob/5b745f5f40fd3155f6abd9f64c04fdaa193df02b/base/operators.jl#L420-L444) + in(p::Pair, d::Dict) ... what else?

**Comment by stevengj** [comment]
No, because the main reason to have `Pair` is to use the `=>` syntax, but Compat can't really do this.  Although `@compat` could change `a => b` into `Pair(a,b)`, this transformation isn't correct in 0.3 if `a => b` appears inside a `Dict` construction.

**Comment by hayd** [comment]
> this transformation isn't correct in 0.3 if a => b appears inside a Dict construction.

is there no way to make that part work?

**Comment by stevengj** [comment]
@hayd, I guess it's possible for `@compat` to set a flag when it enters a `Dict` construction or comprehension as it recurses through an expression, but it will be tricky to make it robust for arbitrarily nested expressions.

**Comment by hayd** [comment]
see also https://github.com/JuliaLang/DataStructures.jl/pull/126
