### ISSUE TITLE
Incorrect deprecation for contains(str, regex) in Julia v0.7.0

### ISSUE THREAD

**Issue by ltf-canada** [JuliaLang/Compat.jl#610]
contains(str, needle::String) has been deprecated. However from the release notes:

ismatch(regex, str) has been deprecated in favor of contains(str, regex)

It looks as if the deprecation is looking for something like an AbstractString and incorrectly catches the contains(str, regex) case.

**Comment by ltf-canada** [comment]
It appears that this deprecation message is very misleading.

Function contains does not exist in Julia v1.0.0 at all. Instead the above deprecation message should state occursin(regex, str) instead.

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0.
