### ISSUE TITLE
@test_logs needed for 0.6?

### ISSUE THREAD

**Issue by richardreeve** [JuliaLang/Compat.jl#611]
`@test_warn` is broken on 0.7 and 1.0 JuliaLang/julia#28549 and we should be using `@test_logs` instead, but that does not exist on 0.6... can this be provided in Compat, as apart from that my package is complete and testing well across 0.6-1.0!

**Comment by fredrikekre** [comment]
Simce the internals habe changed quite a bit I would just use an `if` around a version check and use `@test_warn` on 0.6 and `@test_logs` otherwise.

**Comment by richardreeve** [comment]
Okay, I thought of doing that. The problem is that because `@test_logs` is a macro it fails on 0.6 even inside the `if VERSION` statement because it's not defined :(.

**Comment by fredrikekre** [comment]
You can use `@static if VERSION ...`.

**Comment by martinholters** [comment]
Closing as outdated since we've dropped support for Julia prior to 1.0.
