### ISSUE TITLE
No support for Random.seed!

### ISSUE THREAD

**Issue by galenlynch** [JuliaLang/Compat.jl#615]
[#27726](https://github.com/JuliaLang/julia/issues/27726) deprecated `srand` for `Random.seed!` but I see no mention of either function in this repository. I can't figure out how to make these functions work in both 0.6 and 1.0

**Comment by fredrikekre** [comment]
#601

**Comment by galenlynch** [comment]
Ah I missed that, thanks for pointing it out! I'll just sit tight then.

**Comment by martinholters** [comment]
Fixed long ago by #601.
