### ISSUE TITLE
argmin/argmax not defined for Tuples and maybe others

### ISSUE THREAD

**Issue by anowacki** [JuliaLang/Compat.jl#621]
Although `argmin`/`argmax` on v0.7+ are defined on anything you can iterate (via `findmin`/`findmax`), that's not the case within Compat at the moment.  Currently, they are defined for:

1. `AbstractArray`
2. `AbstractVector`
3. `Associative`

Therefore, you can't currently write compatible code if you want to use `Tuple`s:

```julia
julia> VERSION
v"0.6.3"

julia> using Compat

julia> argmin((1, 2, 3.0))
ERROR: MethodError: no method matching argmin(::Tuple{Int64,Int64,Int64})
Closest candidates are:
  argmin(::AbstractArray{T,1} where T) at /Users/nowacki/.julia/v0.6/Compat/src/Compat.jl:1401
  argmin(::AbstractArray) at /Users/nowacki/.julia/v0.6/Compat/src/Compat.jl:1400
  argmin(::Associative) at /Users/nowacki/.julia/v0.6/Compat/src/Compat.jl:1402
```

Works fine with `indmin`/`indmax`, of course:

```julia
julia> indmin((1, 2, 3.0))
1
```

**Comment by martinholters** [comment]
This is only fixed for the `Tuple` part, not for the "and maybe others", because there is not necessarily a generally valid way to implement this in 0.6. But we can re-open this issue or open another one if the need for a specific "other" one arises.
