### ISSUE TITLE
eachrow, eachcol, eachslice support

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/Compat.jl#639]
For people supporting 1.1 and 1.0,
this is useful.

https://github.com/JuliaLang/julia/issues/29749

**Comment by jiegillet** [comment]
I'd be happy to do a PR for this, as my package already uses `Compat` for `isnothing`, but has an ugly `if VERSION < v"1.1"` thing in it for `eachrow`. 
I think I can mostly figure out how to get started on the PR, but I don't know how to get the `v"1.1.0-DEV.XXX"` precise number from the PR listed above.

**Comment by oxinabox** [comment]
> I don't know how to get the v"1.1.0-DEV.XXX" precise number from the PR listed above.

Don't bother, noone is using `-DEV` versions of `1.1`
having it down to the exact build number is only useful for while that version is at HEAD.

**Comment by martinholters** [comment]
Fixed by #658.
