### ISSUE TITLE
eachindex

### ISSUE THREAD

**Issue by garrison** [JuliaLang/Compat.jl#64]
Following the discussion at JuliaLang/julia#10858, I realized that `eachindex` is not implemented in Compat for julia 0.3.  Might it make sense to implement it?

**Comment by mbauman** [comment]
There's no support for CartesianIndexing in 0.3 (nor could it be feasibly supported in Compat), but a definition like

```julia
eachindex(A::AbstractArray) = 1:length(A)
```

would work perfectly in all situations.  It just won't be as fast in 0.3 for Sparse/SubArray/etc.  I think it makes sense.

**Comment by timholy** [comment]
Good idea. It would be a good thing to have to allow people to start changing packages.

**Comment by lindahua** [comment]
+100!

This is very useful in various statistics functions.

**Comment by lindahua** [comment]
should also add ``linearindexing``, ``LinearFast``, and ``LinearSlow``. They are useful for customized array types.

**Comment by mbauman** [comment]
I'm not sure we can add those, @lindahua. Especially since they aren't exported and Cartesian indexing without staged functions looks extremely different.

**Comment by lindahua** [comment]
Never mind. I can deal with those in packages. I am curious how you got the version number, like ``0.4.0-dev+1624``.

**Comment by timholy** [comment]
https://github.com/JuliaLang/Compat.jl#developer-tips
