### ISSUE TITLE
Compat: Forging ahead in the 1.x era

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/Compat.jl#651]
Now that Julia versions 0.6 and 0.7 are [officially unmaintained](https://discourse.julialang.org/t/julia-0-6-and-0-7-are-now-officially-unmaintained/20449), I would propose that we drop support for versions prior to 1.0 and focus on providing features from 1.1 and later to 1.0. That would allow Compat to be simplified tremendously, and may help spur developer interest in contributing, since no one cares (or wants to care) about 0.6 anymore.

**Comment by martinholters** [comment]
In preparation of #646 I have created a branch locally with everything pre-0.7 removed to see what remains (and check whether any of it should be deprecated). I can clean that up and push it next week. If we want to go ahead here, we should do that first and then tag 2.0.0 I guess.

**Comment by ararslan** [comment]
I also have a local branch with these changes that I can push later today. I was about to push it last night but I hadn't finished updating the README.

**Comment by martinholters** [comment]
Ok, go ahead with yours, then.

**Comment by martinholters** [comment]
@lobingera want to comment on your :-1:? Do you actually write code where you want to use 1.x features while maintaining compatibility with 0.6?

**Comment by lobingera** [comment]
Let's say, i see some questions/complaints showing up in https://github.com/JuliaGraphics/Cairo.jl context when 0.6 compatibility is not available anymore. I've seen this a few times when we tried to reduce 'old' options. There seems to be a lot of code out there that not constantly update to newer julia and Cairo seems always to be entangled for creating graphic output. 
I understand the need to keep Compat lean but at the same time this means branching at the packages they use it.

**Comment by ararslan** [comment]
0.6 will continue to work just fine, you just won't be able to use as many 1.1 features while continuing to support 0.6. That seems like a reasonable tradeoff to me.

**Comment by davidanthoff** [comment]
I think it would be entirely fine to drop julia 0.6 support _going forward_ for a package like Cairo.jl. That would break nothing on existing julia 0.6 installations, and simplify things a lot going forward.

**Comment by oxinabox** [comment]
I think for 1.x Compat should support from most recent LTS (currently and probably forever 1.0) onwards.
