### ISSUE TITLE
Can we have `*(::Union{Regex, AbstractString, AbstractChar}...)` into `Compat.jl`?

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/Compat.jl#672]
Can the [PR #23422](https://github.com/JuliaLang/julia/pull/23422) be added to `Compat.jl`? It could be wonderful if we could use `*` or `^` for `Regex` in pre-1.3 Julia versions.

**Comment by martinholters** [comment]
From a brief glance, that should be quite doable, if anyone wants to take a stab at it.

**Comment by martinholters** [comment]
Closing as Compat now targets Julia 1.6 or later, where this is not needed anymore.
