### ISSUE TITLE
5-arg mul!s?

### ISSUE THREAD

**Issue by jagot** [JuliaLang/Compat.jl#681]
Should the 5-arg `mul!`s be included in Compat.jl, i.e. `mul!(w, A, b, α=1, β=0)`? I would like to start writing code like this, but retain compatibility with Julia 1.x, x < 3.

**Comment by oxinabox** [comment]
would it be acceptable to put in a very naive version of it?

**Comment by jagot** [comment]
Actually, I basically dropped Julia < 1.5, so naive works for me :)
