### ISSUE TITLE
add @artifact_str

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/Compat.jl#684]
when creating an artifact with julia 1.3 the BinaryBuilder pipeline drops everything in the right place such that I could depend on the newly created jll even for pre 1.3 packages. Thus, an `artifact"dependency"` which could be made via the recommended pre 1.3 [solution](https://github.com/JuliaPackaging/Yggdrasil#binaryproviderjl) using BinaryProvider.jl would be perfect and to my understanding in the scope of this package

**Comment by martinholters** [comment]
Closing as Compat now targets Julia 1.6 or later, where this is not needed anymore.
