### ISSUE TITLE
Tag 0.5.0 in METADATA.jl

### ISSUE THREAD

**Issue by jhasse** [JuliaLang/Compat.jl#70]
Hi!

Just wanted to ask when 0.5.0 is going to be tagged in METADATA.jl?

**Comment by tkelman** [comment]
0.5.0 looks like it's the same commit as 0.4.0, so might have just been a typo on @stevengj's part. I'm not sure how @StefanKarpinski wound up tagging 0.3.8 when we already have 0.4.0 and 0.4.1 (forgot to run `Pkg.update()` or `Pkg.checkout("Compat")` maybe?), but that tag should probably be redone.

**Comment by IainNZ** [comment]
Oh wow. Maybe tag a 0.5.0 just to be completely unambiguous and get past this situation?

**Comment by tkelman** [comment]
That would be preferred over 0.4.1 and 0.3.8, wouldn't it? There already is a 0.5.0 git tag in this repo, that has not been committed to metadata yet. The 0.3.8 tag here and in metadata is strictly newer than 0.4.0 and 0.4.1, which is confusing.

**Comment by stevengj** [comment]
Whoops, yes, that was a typo on my part.  I accidentally tagged twice, so I didn't push 0.5 in the metadata, but I forgot to delete the tag from the repo.  Can we just delete the tag?

**Comment by StefanKarpinski** [comment]
I apologize both for screwing this up and for writing tooling that makes it too easy to screw this up. Mea culpa squared :-\

**Comment by tkelman** [comment]
let's delete the 0.5.0 tag, and re-tag master as 0.4.2

**Comment by tkelman** [comment]
Okay, I figured out how to delete the 0.5.0 tag (anybody who's likely to do `git push --tags` to this repo in the future, please do the same on your local clones).

What do we do about the 0.3.8 tag?
