### ISSUE TITLE
Add `endswith` with regex check

### ISSUE THREAD

**Issue by siddharthlal25** [JuliaLang/Compat.jl#707]
For pre-Julia v1.2, `endswith` supports signature:
```
endswith(::String, ::String)
```
It would be nice to add this version (implemented in Julia 1.2 and above)
```
endswith(::String, ::Regex)
```

**Comment by mcabbott** [comment]
It looks like this was added in https://github.com/JuliaLang/julia/pull/29790/files, adding it is just a matter of copying that (and its tests) into this package, and making a pull request. The readme explains [here](https://github.com/JuliaLang/Compat.jl#developer-tips) how to get the correct version number bound.

**Comment by nickrobinson251** [comment]
https://github.com/JuliaLang/Compat.jl/pull/733
