### ISSUE TITLE
Compat making tuples in function call (erronously?)

### ISSUE THREAD

**Issue by zenna** [JuliaLang/Compat.jl#71]
Is this desired behaviour?

```julia
julia> min(@compat Int32(-100), @compat Int32(100))
ERROR: MethodError: `min` has no method matching min(::(Int32,Int32))
Closest candidates are:
  min(::Any, ::Any)
  min(::Any, ::Any, ::Any)
  min(::Any, ::Any, ::Any, ::Any...)
```

If so, how can I do what I inteded (call `min` with two `Int32`s)

**Comment by simonster** [comment]
Hi Zenna! `@compat Int32(-100), @compat Int32(100)` is actually parsed as `@compat(Int32(-100), @compat Int32(100))`. You probably want `min(@compat(Int32(-100)), @compat(Int32(100)))` or `@compat min(Int32(-100), Int32(100))`.
