### ISSUE TITLE
Need a macro for Nothing/Void

### ISSUE THREAD

**Issue by sebastiang** [JuliaLang/Compat.jl#72]
... unless this confusing change is going to be unchanged?

**Comment by andrewcooke** [comment]
i was just about to file this.  what i've done in the meantime is just add

```
if VERSION < v"0.4-" typealias Void Nothing end
```

to my code.

**Comment by yuyichao** [comment]
This was closed by https://github.com/JuliaLang/Compat.jl/pull/139
