### ISSUE TITLE
too many dependencies

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/Compat.jl#764]
As we all know, *many* packages depend on Compat. Unfortunately, Compat depends on every standard library package, which is a problem for static compilation via e.g. `filter_stdlibs` in PackageCompiler --- you can't use a simple compatibility shim function without bringing in the REPL, Pkg, etc. Is there any possible path to removing these dependencies? I see we have binding deprecations for them here, but I don't remember what they do exactly.

**Comment by martinholters** [comment]
From memory, some code archaeology might (or might not) confirm: When things started to be moved into stdlibs and you had to do `using StdLib`, Compat provided `Compat.StdLib` which was just `StdLib` on the then-current Julia version and some self-constructed module on older Julia versions that tried to mimic the then-current version of ` StdLib`. We can probably remove the deprecations and the dependencies along with them and call the result `v4.0`.
