### ISSUE TITLE
Backport stack to 3.x branch

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/Compat.jl#778]
@ararslan - #777 also needs to be backported to 3.46 branch, as 4.x branches support only Julia 1.6 and newer.

**Comment by bkamins** [comment]
@ararslan - do you have enough Compat.jl rights to make this backport?

**Comment by ararslan** [comment]
Yep! PR for that up in #779.

**Comment by martinholters** [comment]
Closed by #779.
