### ISSUE TITLE
2-arg @inferred problem

### ISSUE THREAD

**Issue by alyst** [JuliaLang/Compat.jl#795]
I'm trying to use 2-arg `@inferred` macro from Compat 3.46.1, but I'm getting
```
ERROR: LoadError: LoadError: LoadError: UndefVarError: _args_and_call not defined
```
See [JuliaStats/Clustering.jl#248](https://github.com/JuliaStats/Clustering.jl/actions/runs/4475285895/jobs/7864558642?pr=248).

I guess that's because `_args_and_call()` is actually defined in *Test*, not *Base*.

**Comment by martinholters** [comment]
Fixed by #796
