### ISSUE TITLE
compat erroneously creates 1-entry tuple

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/Compat.jl#93]
The following is in a very recent commit of Julia 0.4:

```julia
julia> c = Tuple{Int,Int}((4,3))
(4,3)

julia> c = (@compat Tuple{Int,Int})((4,3))
(4,3)

julia> typealias d Tuple{Int,Int}
Tuple{Int64,Int64}

julia> typealias e (@compat Tuple{Int,Int})
(Tuple{Int64,Int64},)
```

Shouldn't e also be defined as Tuple{Int,Int} rather than (Tuple{Int,Int},)?

**Comment by simonster** [comment]
`typealias e (@compat Tuple{Int,Int})` appears to behave the same as `typealias e (Tuple{Int,Int})`. You probably want `typealias e @compat(Tuple{Int,Int})`. In most contexts, there's no difference since parenthesizing an expression does not change its meaning, but evidently here there is.
