### ISSUE TITLE
Nullable with subtype

### ISSUE THREAD

**Issue by andrewcooke** [JuliaLang/Compat.jl#94]
I am having a problem when I assign a value to a Nullable which it a sub-type of the type contained by the Nullable.  This works in 0.4, but not with Compat.

Here is the problem:

```
julia> abstract Parent

julia> immutable Child <: Parent end

julia> type Container x::Nullable{Parent} end

julia> c = Container(Child())
ERROR: `convert` has no method matching convert(::Type{Nullable{Parent}}, ::Child)
 in Container at no file
```

However, I have no idea how you solve this because:

```
julia> convert{T,S<:T}(::Type{Nullable{T}}, s::S) = Nullable{T}(s)
ERROR: T not defined
```

**Comment by andrewcooke** [comment]
PS Otherwise, though, thanks for an amazingly useful package.

**Comment by johnmyleswhite** [comment]
This pattern, `convert{T,S<:T}`, is what's sometimes called triangular dispatch. To my knowledge, it doesn't work in Julia yet.

I wonder if you want to be working with a parametric type for Container (e.g. `Container{T}`) rather than something non-concrete like `Nullable{Parent}`.

**Comment by andrewcooke** [comment]
but the code i posted works in 0.4 (i'm using a 6 days old checkout).

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4995 (2015-05-25 20:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 96cc970 (6 days old master)
|__/                   |  x86_64-suse-linux

julia> abstract Parent

julia> immutable Child <: Parent end

julia> type Container x::Nullable{Parent} end

julia> c = Container(Child())
Container(Nullable(Child()))
```

(i can fix my code in various ways, and it may not be great how it is, but i was raising this issue because the code above works in 0.4, but not in 0.3, even when Compat is used).

**Comment by andrewcooke** [comment]
maybe my hamfisted attempt at guessing how julia works is misleading.  ignore the final part of my first post if it helps.

**Comment by johnmyleswhite** [comment]
I think something has changed that I don't fully understand in either (a) how type parameters work when doing dispatch or (b) the way that `convert` relates to constructors.

You can raise the same problem you're hitting without involving user types by executing `convert(Nullable{Integer}, 1)`. Contrast Julia 0.3:

```jl
julia> @which convert(Nullable{Integer}, 1)
convert(T,x) at base.jl:13
```

with Julia 0.4:

```jl
julia> @which convert(Nullable{Integer}, 1)
convert{T}(::Type{Nullable{T}}, x::T) at nullable.jl:15
```

**Comment by andrewcooke** [comment]
huh.  well i've been poking through issues and changes and finally realised you wrote this stuff, so i am giving up :)

**Comment by johnmyleswhite** [comment]
I'm sure someone who understands the issues involved better than I do will chime in. While we wait, I wonder if redesigning things to avoid having a type `Nullable{Parent}` will solve multiple problems.

**Comment by andrewcooke** [comment]
https://github.com/JuliaLang/julia/issues/8974#issuecomment-62685279 ?

**Comment by johnmyleswhite** [comment]
That does seem relevant. And I do find the covariant matching confusing.
